name: Hello world

on: [push]

jobs:
  helllo:
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo "Hello world"

  lorem:
    runs-on: ubuntu-latest

    steps:
      - name: LS
        run: ls -al
