name: Hello world

on: [push, pull_request]

jobs:
  helllo:
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo "Hello world"

  lorem:
    runs-on: ubuntu-latest
    needs: [helllo]

    steps:
      - name: pwd
        run: pwd

      - name: LS
        run: ls -al

      - name: touch file
        run: touch file.txt

      - name: set text
        run: echo "lorem ipsum" >> file.txt

      - name: read file
        run: cat file.txt
